/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as pagesIndexRouteImport } from './routes/(pages)/index'
import { Route as authSignUpIndexRouteImport } from './routes/(auth)/sign-up/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'

const pagesIndexRoute = pagesIndexRouteImport.update({
  id: '/(pages)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpIndexRoute = authSignUpIndexRouteImport.update({
  id: '/(auth)/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof pagesIndexRoute
  '/login/': typeof authLoginIndexRoute
  '/sign-up/': typeof authSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof pagesIndexRoute
  '/login': typeof authLoginIndexRoute
  '/sign-up': typeof authSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(pages)/': typeof pagesIndexRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/sign-up/': typeof authSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login/' | '/sign-up/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/sign-up'
  id: '__root__' | '/(pages)/' | '/(auth)/login/' | '/(auth)/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  pagesIndexRoute: typeof pagesIndexRoute
  authLoginIndexRoute: typeof authLoginIndexRoute
  authSignUpIndexRoute: typeof authSignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(pages)/': {
      id: '/(pages)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof pagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up/': {
      id: '/(auth)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof authSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  pagesIndexRoute: pagesIndexRoute,
  authLoginIndexRoute: authLoginIndexRoute,
  authSignUpIndexRoute: authSignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
